sudo: required
services:
    - docker

before_install:
    - docker build -t imijatovic/docker-react -f Dockerfile.dev .   
 
script:
    - docker run -e CI=true imijatovic/docker-react npm run test  